#! /bin/sh
#
# chkconfig: 345 80 20

. /etc/rc.d/init.d/functions
RETVAL=0
args1="/home/checker/monitoring/config.cfg"
args2="/home/checker/monitoring/monitoring.cfg"
start () {
    echo "Starting checker"
    daemon --user=checker /home/checker/monitoring/checker3.py  $args1 $args2 >> /home/checker/stdout 2>>/home/checker/stderr &
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/checker/checker
    echo
    return $RETVAL
}

stop () {
    echo -n "Stopping $prog: "
    kill `cat /tmp/checker3.pid` && rm -f /tmp/checker3.pid
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/checker/checker
    echo
    return $RETVAL
}
case $1 in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start                                                                     
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	;;
esac

RETVAL=$?

exit $RETVAL
